-- Lead-generation layer on top of the monitoring engine.
--
-- Three additive tables + a view replacement:
--   opportunities   — deterministic derivation over quality-ok insights: the ranked
--                     "who to contact, when, and why" queue the Lead Generation view works.
--   drafts          — AI-generated outreach emails per opportunity (on-demand only,
--                     never pre-generated by cron; history kept, latest wins in UI).
--   lead_candidates — entities mentioned alongside watched accounts by the extract
--                     pass (new-lead discovery), proposed for one-click watchlisting.
--   v_monitoring_accounts — same shape as 0001, but timestamps become ISO-8601 UTC
--                     strings; all display formatting moves to the client.

-- ---------------------------------------------------------------------------
-- opportunities — one row per qualifying insight (unique insight_id keeps the
-- derivation idempotent). score = round(100 * confidence * urgencyWeight *
-- recencyDecay), computed in pipeline/opportunities.ts — derived, not arbitrary.
-- ---------------------------------------------------------------------------
create table if not exists opportunities (
  id               uuid primary key default gen_random_uuid(),
  entity_id        uuid not null references entities(id) on delete cascade,
  insight_id       uuid not null unique references insights(id) on delete cascade,
  signal_type      text,
  score            integer not null check (score between 0 and 100),
  status           text not null default 'new'
                     check (status in ('new', 'contacted', 'qualified', 'dismissed')),
  why_now          text not null,
  suggested_action text not null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index if not exists opportunities_queue_idx on opportunities(status, score desc);
create index if not exists opportunities_entity_idx on opportunities(entity_id);

-- ---------------------------------------------------------------------------
-- drafts — generated outreach per opportunity. facts_used holds the verbatim
-- evidence excerpts the model claims it relied on; `grounded` is the server-side
-- verification that each one substring-matches the supplied evidence.
-- ---------------------------------------------------------------------------
create table if not exists drafts (
  id             uuid primary key default gen_random_uuid(),
  opportunity_id uuid not null references opportunities(id) on delete cascade,
  subject        text not null,
  body           text not null,
  facts_used     jsonb not null default '[]'::jsonb,
  grounded       boolean not null default true,
  model          text,
  edited         boolean not null default false,
  created_at     timestamptz not null default now()
);
create index if not exists drafts_opp_idx on drafts(opportunity_id, created_at desc);

-- ---------------------------------------------------------------------------
-- lead_candidates — new-lead discovery inbox. Upserted on (normalized_name, type)
-- so repeat mentions bump mention_count/last_seen_at instead of duplicating.
-- Status never downgrades from added/dismissed back to proposed.
-- ---------------------------------------------------------------------------
create table if not exists lead_candidates (
  id               uuid primary key default gen_random_uuid(),
  name             text not null,
  normalized_name  text not null,
  type             text not null check (type in ('person', 'company')),
  relationship     text,        -- partner/customer/competitor/investor/executive/vendor/other
  reason           text,        -- e.g. "named as new logistics partner of BMW Group"
  source_entity_id uuid references entities(id) on delete set null,
  finding_id       uuid references findings(id) on delete set null,
  evidence         jsonb not null default '[]'::jsonb, -- [{source_url, excerpt}]
  status           text not null default 'proposed'
                     check (status in ('proposed', 'added', 'dismissed')),
  added_entity_id  uuid references entities(id) on delete set null,
  mention_count    integer not null default 1,
  first_seen_at    timestamptz not null default now(),
  last_seen_at     timestamptz not null default now(),
  unique (normalized_name, type)
);
create index if not exists lead_candidates_status_idx on lead_candidates(status, last_seen_at desc);

-- ---------------------------------------------------------------------------
-- v_monitoring_accounts — same output contract as 0001, with one change:
-- `signals[].time` and `latest` are now ISO-8601 UTC strings (no minutes-level
-- pretty-printing in SQL). The client (app/src/lib/format.ts) owns display.
-- ---------------------------------------------------------------------------
-- `latest` changes type (timestamptz -> text), which create-or-replace forbids.
drop view if exists v_monitoring_accounts;
create view v_monitoring_accounts as
with recent as (
  select i.*,
         row_number() over (partition by i.entity_id order by coalesce(i.published_at, i.created_at) desc) as rn
  from insights i
  where i.quality = 'ok'
)
select
  e.id,
  e.name,
  coalesce(e.profile->>'tier', case when e.type = 'company' then 'Strategic' else 'Expansion' end) as tier,
  coalesce(max(case when r.urgency = 'High' then 'High'
                    when r.urgency = 'Medium' then 'Medium'
                    else 'Low' end), 'Low') as urgency,
  coalesce(round(avg(r.confidence) * 100)::int, 0) as score,
  (select count(*) from sources s where s.entity_id = e.id) as sources,
  to_char(max(coalesce(r.published_at, r.created_at)) at time zone 'utc',
          'YYYY-MM-DD"T"HH24:MI:SS"Z"') as latest,
  coalesce(e.profile->'notifications', '{"email": true, "webhook": false}'::jsonb) as notifications,
  (array_agg(r.summary order by coalesce(r.published_at, r.created_at) desc))[1] as summary,
  coalesce(
    jsonb_agg(
      jsonb_build_object(
        'type', r.signal_type,
        'time', to_char(coalesce(r.published_at, r.created_at) at time zone 'utc',
                        'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
        'title', r.headline,
        'evidence', r.why_it_matters,
        'urgency', r.urgency
      ) order by coalesce(r.published_at, r.created_at) desc
    ) filter (where r.rn <= 8),
    '[]'::jsonb
  ) as signals
from entities e
left join recent r on r.entity_id = e.id
group by e.id;
